main = "index.js"
name = "feedbox"
route = "feedbox.h11.io/*"
workers_dev = false
no_bundle = true

compatibility_date = "2023-08-09"
compatibility_flags = [ "nodejs_compat" ]

[placement]
mode = "smart"
