main = "index.js"
name = "backup"
route = "worker.h11.io/backup*"

compatibility_date = "2023-08-09"
compatibility_flags = [ "nodejs_compat" ]

kv_namespaces = [{ binding = "BA", id = "fb7f86b3d7fb42bc8bb5ed43907a6479" }]
r2_buckets = [{ binding = "R2apac", bucket_name = "apac" }]

[placement]
mode = "smart"
