main = "index.js"
name = "backup"
route = "worker.h11.io/backup*"

compatibility_date = "2022-05-12"
compatibility_flags = ["r2_public_beta_bindings"]

r2_buckets = [
    { binding = "R2Backup", bucket_name = "backup" }
]
