main = "index.js"
name = "r2-share"
route = "worker.h11.io/share*"

compatibility_date = "2023-07-25"

kv_namespaces = [{ binding = "BA", id = "fb7f86b3d7fb42bc8bb5ed43907a6479" }]
r2_buckets = [{ binding = "R2share", bucket_name = "share" }]

[placement]
mode = "smart"
