main = "index.js"
name = "proxy-list"
route = "worker.h11.io/proxy-list*"

compatibility_date = "2023-08-09"
compatibility_flags = [ "nodejs_compat" ]

kv_namespaces = [{ binding = "BA", id = "fb7f86b3d7fb42bc8bb5ed43907a6479" }]

[placement]
mode = "smart"
