main = "index.js"
name = "current-ip"
route = { pattern = "worker.h11.io/current-ip*", zone_id = "6cffee8a847ad1565b9cb2572cce3a04" }

compatibility_date = "2022-05-12"

kv_namespaces = [{ binding = "IP", id = "3c2b8c77135540e39669e16c79b980c1" }]
