name: badip

on:
    push:
        branches:
            - master
        paths:
            - '*'
            - '_common/**'
            - 'badip/**'
            - '.github/workflows/badip.yml'

jobs:
    deploy:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2.3.1
            - uses: actions/setup-node@v1.4.2
              with:
                  node-version: '14.x'
            - uses: actions/cache@v2.0.0
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-
            - run: npm i -g pnpm@5.2
            - name: build
              run: |
                  pnpm install
                  make build PROJ=badip
            - name: deploy
              working-directory: ./badip
              run: |
                  pnpm add @cloudflare/wrangler
                  echo "$FAUNA_KEY" | pnpx wrangler secret put 'FAUNA_KEY'
                  echo "$ROLLBAR_KEY" | pnpx wrangler secret put 'ROLLBAR_KEY'
                  pnpx wrangler publish
              env:
                  FAUNA_KEY: ${{ secrets.FAUNA_KEY }}
                  ROLLBAR_KEY: ${{ secrets.ROLLBAR_KEY }}
                  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
