name: logplex

on:
    push:
        branches:
            - master
        paths:
            - '*'
            - '_common/**'
            - 'logplex/**'
            - '.github/workflows/logplex.yml'

jobs:
    deploy:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2.3.1
            - uses: actions/setup-node@v1.4.2
              with:
                  node-version: '14.x'
            - uses: actions/cache@v2.0.0
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-
            - run: npm i -g pnpm@5.2
            - name: build
              run: |
                  pnpm install
                  make build PROJ=bcc
            - name: deploy
              working-directory: ./bcc
              run: |
                  pnpm add @cloudflare/wrangler
                  echo "$BCC_WEBHOOK_PATH" | pnpx wrangler secret put 'BCC_WEBHOOK_PATH'
                  echo "$BCC_BOT_TOKEN" | pnpx wrangler secret put 'BCC_BOT_TOKEN'
                  echo "$FAUNA_KEY" | pnpx wrangler secret put 'FAUNA_KEY'
                  echo "$ROLLBAR_KEY" | pnpx wrangler secret put 'ROLLBAR_KEY'
                  pnpx wrangler publish
                  curl "https://api.telegram.org/bot${BCC_BOT_TOKEN}/setWebhook?url=https%3A%2F%2Fworker.h11.io%2Ftelegram%2Fbcc%2F${BCC_WEBHOOK_PATH}"
              env:
                  BCC_WEBHOOK_PATH: ${{ secrets.BCC_WEBHOOK_PATH }}
                  BCC_BOT_TOKEN: ${{ secrets.BCC_BOT_TOKEN }}
                  FAUNA_KEY: ${{ secrets.FAUNA_KEY }}
                  ROLLBAR_KEY: ${{ secrets.ROLLBAR_KEY }}
                  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
