name: mzbot

on:
    push:
        branches:
            - master
        paths:
            - '*'
            - '_common/**'
            - 'mzbot/**'
            - '.github/workflows/mzbot.yml'

jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2.0.0
            - uses: actions/setup-node@v1.1.0
              with:
                  version: '14.x'
            - run: echo "::set-output name=dir::$(yarn cache dir)"
              id: yarn-cache
            - uses: actions/cache@v1.1.2
              with:
                  path: ${{ steps.yarn-cache.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: ${{ runner.os }}-yarn-
            - name: build
              run: |
                  yarn install
                  make build PROJ=mzbot
            - name: deploy
              working-directory: ./mzbot
              run: |
                  yarn add @cloudflare/wrangler
                  yarn wrangler publish
                  echo "$MZBOT_WEBHOOK_PATH" | yarn wrangler secret put 'MZBOT_WEBHOOK_PATH'
                  echo "$MZBOT_BOT_TOKEN" | yarn wrangler secret put 'MZBOT_BOT_TOKEN'
                  echo "$MY_TELEGRAM_CHAT_ID" | yarn wrangler secret put 'MY_TELEGRAM_CHAT_ID'
                  echo "$FAUNA_KEY" | yarn wrangler secret put 'FAUNA_KEY'
                  echo "$ROLLBAR_KEY" | yarn wrangler secret put 'ROLLBAR_KEY'
                  curl "https://api.telegram.org/bot${MZBOT_BOT_TOKEN}/setWebhook?url=https%3A%2F%2Fworker.h11.io%2Ftelegram%2Fmzbot%2F${MZBOT_WEBHOOK_PATH}"
              env:
                  MZBOT_WEBHOOK_PATH: ${{ secrets.MZBOT_WEBHOOK_PATH }}
                  MZBOT_BOT_TOKEN: ${{ secrets.MZBOT_BOT_TOKEN }}
                  MY_TELEGRAM_CHAT_ID: ${{ secrets.MY_TELEGRAM_CHAT_ID }}
                  FAUNA_KEY: ${{ secrets.FAUNA_KEY }}
                  ROLLBAR_KEY: ${{ secrets.ROLLBAR_KEY }}
                  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
