name: sentry

on:
    push:
        branches:
            - master
        paths:
            - '*'
            - '_common/**'
            - 'sentry/**'
            - '.github/workflows/sentry.yml'

jobs:
    deploy:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2.3.1
            - uses: actions/setup-node@v1.4.2
              with:
                  node-version: '14.x'
            - uses: actions/cache@v2.0.0
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-
            - run: npm i -g pnpm@5.2
            - name: build
              run: |
                  pnpm install
                  make build PROJ=sentry
            - name: deploy
              working-directory: ./sentry
              run: |
                  pnpm add @cloudflare/wrangler
                  echo "$TELEGRAM_BOT_TOKEN" | pnpx wrangler secret put 'TELEGRAM_BOT_TOKEN'
                  echo "$MY_TELEGRAM_CHAT_ID" | pnpx wrangler secret put 'MY_TELEGRAM_CHAT_ID'
                  echo "$SENTRY_HOOK_SECRET" | pnpx wrangler secret put 'SENTRY_HOOK_SECRET'
                  pnpx wrangler publish
              env:
                  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
                  MY_TELEGRAM_CHAT_ID: ${{ secrets.MY_TELEGRAM_CHAT_ID }}
                  SENTRY_HOOK_SECRET: ${{ secrets.SENTRY_HOOK_SECRET }}
                  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
